### ISSUE TITLE
zprovozneni pro vyvoj na localhostu

### ISSUE THREAD

**Issue by yedpodtrzitko** [cityvizor/cityvizor#204]
### Popiš chybu

zkousim zprovoznit projekt na localhostu pro vyvoj dle `INSTALLATION.md`, ale skoncil jsem hned pri pokusu o pripojeni k db behem vytvareni admin pristupu:

### Jak chybu nasimulovat
```
$ npm run create-admin 

> cityvizor-server@4.2.0 create-admin /Users/yed/dev/mine/cityvizor/server
> node dist/scripts/create-admin.js

[CONFIG] Loading configuration for environment: development
[DB] DB connection set to yed@cityvizor
[DB] Running migrations
Generating password hash...
Deleting admin user data from database...
(node:75442) UnhandledPromiseRejectionWarning: TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Users/yed/dev/mine/cityvizor/server/node_modules/knex/lib/client.js:348:17
    at tryCatcher (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:75442) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:75442) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:75442) UnhandledPromiseRejectionWarning: TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Users/yed/dev/mine/cityvizor/server/node_modules/knex/lib/client.js:348:17
    at tryCatcher (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/yed/dev/mine/cityvizor/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
(node:75442) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

konfigurace pro databazi v `environment.development.js` mam nastavnou nasledovne:

```
  database: {
    client: 'pg',
    host: 'localhost',
    user: 'yed',
    database: 'cityvizor',
    password: "",
  }
```

ze shellu se k DB pripojim bez problemu:

```
$ psql -Uyed -d cityvizor -h localhost           
Null display is "Ø".
psql (12.3)
Type "help" for help.

cityvizor=# 
```

Zkousel jsem snad vsechny mozny kombinace, grepoval jsem internety na danou chybovou hlasku, ale bez uspechu.

**Comment by lukas-krecan** [comment]
To je blbý. Koukni prosím do CONTRIBUTING.md a zkus to podle toho (ten Docker compose by fungovat měl). Pokud chceš dělat jen na redesignu, stačí ti rozjet věci v redesign adresáři.
